context:
  name: pixi-inject
  version: "0.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/pavelzw/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 822267315e2f7a32abda0210a3730762dc9436d988a1a4329e7d29b1c8997189

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - if: unix
      then: openssl

tests:
  - script:
      - pixi-inject --help

about:
  homepage: https://github.com/pavelzw/pixi-inject
  summary: Inject conda packages into an already existing conda prefix
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/pavelzw/pixi-inject

extra:
  recipe-maintainers:
    - pavelzw
